# Generated by Django 6.0.3 on 2026-03-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, verbose_name='Слово на языке оригинала')),
                ('translation1', models.CharField(max_length=200, verbose_name='Перевод 1')),
                ('translation2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Перевод 2')),
                ('translation3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Перевод 3')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards/', verbose_name='Изображение')),
                ('group', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
    ]
