# Generated by Django 6.0.3 on 2026-03-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_category_card_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='translation1',
        ),
        migrations.RemoveField(
            model_name='card',
            name='translation2',
        ),
        migrations.RemoveField(
            model_name='card',
            name='translation3',
        ),
        migrations.AddField(
            model_name='card',
            name='translation',
            field=models.CharField(default='', max_length=200, verbose_name='Перевод'),
        ),
    ]
